# Generated by Django 4.1 on 2022-09-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=100)),
                ('status_parser', models.BooleanField(default=False)),
                ('exclude_from_search', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount_of_vacancies', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, default='', null=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_skills.jobtracker')),
            ],
        ),
        migrations.CreateModel(
            name='SkillData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('parser_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_skills.parserdata')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_skills.jobtracker')),
            ],
        ),
    ]
