# Generated by Django 4.1 on 2022-09-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parserdata',
            options={'ordering': ['-date']},
        ),
    ]
