# Generated by Django 4.1 on 2022-09-18 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0002_alter_parserdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtracker',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 18, 12, 19, 6, 940220, tzinfo=datetime.timezone.utc)),
        ),
    ]
