# Generated by Django 4.1 on 2022-09-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0004_alter_jobtracker_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserdata',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
