# Generated by Django 4.1 on 2022-09-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0005_alter_parserdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtracker',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='jobtracker',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
    ]
