# Generated by Django 4.1 on 2022-09-21 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_skills', '0006_remove_jobtracker_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtracker',
            name='user_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
