# Generated by Django 4.1 on 2022-09-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0009_alter_jobtracker_user_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilldata',
            options={'ordering': ['-amount']},
        ),
    ]
