# Generated by Django 4.1.1 on 2022-09-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0010_alter_skilldata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilldata',
            options={'ordering': ['-amount', 'name']},
        ),
    ]
