# Generated by Django 4.1.1 on 2022-09-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0011_alter_skilldata_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobtracker',
            table='JobTracker',
        ),
        migrations.AlterModelTable(
            name='parserdata',
            table='ParserData',
        ),
        migrations.AlterModelTable(
            name='skilldata',
            table='SkillData',
        ),
    ]
