# Generated by Django 4.1.1 on 2022-09-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0012_alter_jobtracker_table_alter_parserdata_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobtracker',
            table=None,
        ),
        migrations.AlterModelTable(
            name='parserdata',
            table=None,
        ),
        migrations.AlterModelTable(
            name='skilldata',
            table=None,
        ),
    ]
