# Generated by Django 4.1.1 on 2022-09-27 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_skills', '0013_alter_jobtracker_table_alter_parserdata_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parserdata',
            name='error_log',
        ),
        migrations.RemoveField(
            model_name='skilldata',
            name='tracker',
        ),
        migrations.AddField(
            model_name='jobtracker',
            name='subscribers',
            field=models.ManyToManyField(related_name='job_tracker_subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
