# Generated by Django 4.1.1 on 2022-10-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0015_alter_jobtracker_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtracker',
            name='hh_url',
            field=models.URLField(default='https://hh.ru'),
        ),
    ]
