# Generated by Django 4.1.1 on 2022-10-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0016_jobtracker_hh_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='jobtracker',
            name='areas',
            field=models.ManyToManyField(related_name='job_tracker_areas', to='job_skills.area'),
        ),
    ]
