# Generated by Django 4.1.1 on 2022-10-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0018_alter_area_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name']},
        ),
    ]
