# Generated by Django 4.1.1 on 2022-10-05 15:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0019_alter_area_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtracker',
            name='areas',
        ),
        migrations.AddField(
            model_name='jobtracker',
            name='areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0], size=None),
        ),
    ]
