# Generated by Django 4.1.1 on 2022-10-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0021_alter_jobtracker_areas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.AlterField(
            model_name='area',
            name='hh_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
