# Generated by Django 4.1.1 on 2022-10-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0022_alter_area_options_alter_area_hh_id_alter_area_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['hh_id', 'name'], name='job_skills__hh_id_316a4d_idx'),
        ),
    ]
