# Generated by Django 4.1.1 on 2022-10-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0023_area_job_skills__hh_id_316a4d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='hh_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
