# Generated by Django 4.1.1 on 2022-10-18 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0025_remove_area_job_skills__hh_id_316a4d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtracker',
            name='modified_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobtracker',
            name='search_text',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parserdata',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
