# Generated by Django 4.1.1 on 2022-10-18 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0026_alter_jobtracker_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtracker',
            name='employment_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), db_index=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='jobtracker',
            name='work_experience',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobtracker',
            name='work_schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), db_index=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='jobtracker',
            name='areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_index=True, default=[], size=None),
        ),
    ]
