# Generated by Django 4.1.1 on 2022-10-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0027_jobtracker_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parserdata',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='jobtracker',
            name='hh_url',
            field=models.TextField(default='https://hh.ru'),
        ),
    ]
