# Generated by Django 4.1.1 on 2022-10-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0028_alter_parserdata_options_alter_jobtracker_hh_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtracker',
            name='exclude_from_search',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
