# Generated by Django 4.1.1 on 2022-10-31 17:28

from django.db import migrations, models
import job_skills.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_skills', '0030_alter_jobtracker_areas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtracker',
            name='search_text',
            field=models.CharField(db_index=True, max_length=100, validators=[job_skills.models.validate_search_text]),
        ),
    ]
